7 - created the published schedule table
ctc-uci/aiss-backend pull request #15
Opened 2023-11-19 00:22 UTC by arralia

closes issue #7

2023-11-19 01:56 UTC, ThatMegamind requested changes
Looks pretty good, just some minor comments. I think Michelle will also leave some feedback

2023-11-19 01:56 UTC, ThatMegamind commented on server/schema/published_schedule.sql
> +DROP TABLE [IF EXISTS] published_schedule;
The brackets around [IF EXISTS] are mainly for readability in tutorials, but they're not actually part of the syntax. Try removing the brackets to remove the eslint issues!

2023-11-19 01:56 UTC, michellelin1 commented on server/schema/published_schedule.sql
> +CREATE TABLE [IF NOT EXISTS] published_schedule (
the brackets aren't needed here. the brackets in the tutorial indicate optional fields but when you actually use those options, you don't use the brackets

2023-11-22 23:28 UTC, ThatMegamind approved these changes
Looks good to me!

2023-11-22 23:31 UTC, merged