Make backend routes for Catelog
ctc-uci/aiss-backend pull request #27
Opened 2023-12-01 22:44 UTC by ctc-devops

Authors:
 ### What does this PR contain?
 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #20

2023-12-01 22:44 UTC, ctc-devops commented on routes/catalog.js
> +    console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-12-01 22:44 UTC, ctc-devops commented on routes/catalog.js
> +    console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-12-01 22:44 UTC, ctc-devops commented on routes/catalog.js
> +    console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-12-01 22:44 UTC, ctc-devops commented on routes/catalog.js
> +    console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2023-12-07 01:11 UTC, ThatMegamind requested changes
Overall looks pretty good to us! Just try to address the minor comments (and do them for all routes). Also, if you guys could remove the yarn.lock changes from your PR that would be great!

2023-12-07 01:11 UTC, ThatMegamind commented on routes/catalog.js
> +// SELECT * FROM catalog WHERE id = ?;
Could you guys delete the comment for the query next to each route (e.g. "SELECT * FROM ...")?

2023-12-07 01:11 UTC, ThatMegamind commented on routes/catalog.js
> +    console.log(err);
Could you guys also remove the console logs here?

2023-12-07 01:11 UTC, ThatMegamind commented on routes/catalog.js
> +    res.status(500).json({
Could you guys modify the output of the post request to also return the id of the row being modified? It'll help later with updating the front-end more efficiently

2023-12-13 23:51 UTC, arralia commented on routes/catalog.js
> +    res.status(500).json({
Would you like us to not return success and just return the id of the newly-posted ID? Or do you want post to return both? Also you're just talking about "post", not "put" as well right?

2023-12-13 23:55 UTC, ThatMegamind commented on routes/catalog.js
> +    res.status(500).json({
I think returning both should be good!

2023-12-18 19:52 UTC, ThatMegamind approved these changes
Looks good to us, approved!

2023-12-18 19:55 UTC, merged