Make Backend Routes for Published Schedule
ctc-uci/aiss-backend pull request #29
Opened 2023-12-07 00:34 UTC by ctc-devops

Authors: @seancfong @Philip-Jian 
 ### What does this PR contain?
 
- [x] Mounted route to published schedule in `app.js`
- [x] Added CRUD routes in `routes/publishedSchedule.js`
- [x] Deleted `server/queries/published_schedule.sql`

 ### How did you test these changes?

 ### Attach images (if applicable)

 Closes #19

2023-12-07 00:34 UTC, ctc-devops commented on routes/publishedSchedule.js
> +  try {
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Delete `⏎`
```suggestion
  try {
```

2023-12-07 00:34 UTC, ctc-devops commented on routes/publishedSchedule.js
> +      [id]
🚫 **[eslint]** <[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Insert `,`
```suggestion
      [id],
```

2023-12-20 22:11 UTC, ThatMegamind requested changes
Overall functionally it works pretty well! Just some minor changes to return extra stuff in the requests

2023-12-20 22:11 UTC, ThatMegamind commented on routes/publishedSchedule.js
> +      status: 'Success',
Can you change the post request so the newly inserted id is also returned?

2023-12-20 22:11 UTC, ThatMegamind commented on routes/publishedSchedule.js
> +          ($1, $2, true, $3, $4, $5, $6, $7);
Can you change the post request so that the user can insert the confirmed value rather than defaulting it to true?

2023-12-20 22:11 UTC, ThatMegamind commented on routes/publishedSchedule.js
> +publishedScheduleRouter.post('/', async (req, res) => {
Can you modify the post request to allow `notes` to be null?

2023-12-20 22:11 UTC, ThatMegamind commented on routes/publishedSchedule.js
> +publishedScheduleRouter.delete('/:id', async (req, res) => {
Can you update the delete request so that all data from the recently deleted entry is returned?

2023-12-20 22:11 UTC, ThatMegamind commented on routes/publishedSchedule.js
> +      UPDATE published_schedule
Can you update the query to return all of the data from the entry that was just changed?

2023-12-20 22:11 UTC, ThatMegamind commented on routes/publishedSchedule.js
> +    event_id: eventId,
Can we change the variables from underscores to camelCase here and in the other requests? When it gets called in the front-end it'll already be camelCase.

2024-01-03 19:35 UTC, ThatMegamind approved these changes

2024-01-03 19:35 UTC, merged